Update harbour-vodman-sv.ts
jgressmann/harbour-vodman pull request #10
Opened 2019-04-18 03:20 UTC by eson57

new and changed strings translated

2019-04-18 16:39 UTC, jgressmann requested changes

2019-04-18 16:39 UTC, jgressmann commented on src/vodman-app/translations/harbour-vodman-sv.ts
> +        <translation>Källkoder finns på GitHub</translation>
Please add the link back
```suggestion
        <translation>Källkoder finns på &lt;a href=&quot;https://github.com/jgressmann/harbour-vodman&quot;&gt;GitHub&lt;/a&gt;.</translation>
```

2019-04-18 16:39 UTC, jgressmann commented on src/vodman-app/translations/harbour-vodman-sv.ts
> +        <translation type="unfinished"></translation>
```suggestion
        <translation>Kopiera filväg till urklipp</translation>
```

2019-04-30 16:19 UTC, merged

2019-04-30 16:22 UTC, jgressmann commented
Thank you for your contribution. I merged your changes but had to update/fix some strings (see review notes). You may want to have another look.

2019-04-30 17:43 UTC, eson57 commented
Looks OK to me.